# **Artificial Neural Network**

Importing the Libraries

In [86]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [87]:
tf.__version__

'2.4.0'

In [88]:
import io
url = 'https://raw.githubusercontent.com/sivatejachigicherla/Deep_Learning_MasterClass/main/Volume%201%20-%20Supervised%20Deep%20Learning/Part%201%20-%20Artificial%20Neural%20Networks%20(ANN)/Section%202%20-%20Part%201%20-%20ANN/Churn_Modelling.csv'
dataset = pd.read_csv(url)
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [89]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [90]:
y

array([1, 0, 1, ..., 1, 1, 0])

Encoding categorical data

In [91]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #Label Encoding the "Gender" column

In [92]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [93]:
from sklearn.compose import ColumnTransformer  #One Hot Encoding the "Geography" column
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [94]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [95]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [96]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Initializing the ANN**

In [68]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [69]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [70]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [71]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Part 3 - Training the ANN

In [72]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [73]:
ann.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 941us/step - loss: 0.5430 - accuracy: 0.7870
Epoch 2/100
800/800 [==============================] - 1s 920us/step - loss: 0.4478 - accuracy: 0.7996
Epoch 3/100
800/800 [==============================] - 1s 913us/step - loss: 0.4174 - accuracy: 0.8228
Epoch 4/100
800/800 [==============================] - 1s 908us/step - loss: 0.4036 - accuracy: 0.8281
Epoch 5/100
800/800 [==============================] - 1s 924us/step - loss: 0.4062 - accuracy: 0.8171
Epoch 6/100
800/800 [==============================] - 1s 909us/step - loss: 0.3826 - accuracy: 0.8355
Epoch 7/100
800/800 [==============================] - 1s 922us/step - loss: 0.3640 - accuracy: 0.8483
Epoch 8/100
800/800 [==============================] - 1s 916us/step - loss: 0.3646 - accuracy: 0.8497
Epoch 9/100
800/800 [==============================] - 1s 916us/step - loss: 0.3667 - accuracy: 0.8462
Epoch 10/100
800/800 [==============================] - 1s 918us/step - l

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [74]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [75]:
y_pred = ann.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.5)
print(y_pred)

[[0.18575874]
 [0.2957816 ]
 [0.09037185]
 ...
 [0.1931333 ]
 [0.14230233]
 [0.16374251]]
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 208  197]]


0.863

K Fold Cross Validation


In [82]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
def build_classifier():
    ann = tf.keras.models.Sequential()
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])    
    return ann
ann = KerasClassifier(build_fn= build_classifier, batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator= ann, X=X_train, y=y_train, cv= 10,n_jobs= -1)
accuracies

array([0.78625   , 0.78375   , 0.79750001, 0.78250003, 0.8125    ,
       0.81      , 0.78750002, 0.79374999, 0.80374998, 0.8075    ])

In [83]:
mean = accuracies.mean()
mean

0.7965000033378601

In [84]:
std  =  accuracies.std()
std

0.010793511387064502

Parameter Tuning

In [105]:
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
def build_classifier(optimizer):
    ann = tf.keras.models.Sequential()
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    ann.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])    
    return ann
ann = KerasClassifier(build_fn= build_classifier)
parameters = {'batch_size': [25,32],
              'nb_epoch':[100,500],
              'optimizer': ['adam','rmsprop']}
grid_search = GridSearchCV(estimator = ann,
                           param_grid = parameters,
                           scoring = 'accuracy', cv = 10)
grid_search = grid_search.fit(X_train, y_train) 
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

288/288 [==============================] - 1s 970us/step - loss: 0.5928 - accuracy: 0.7119


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


250/250 [==============================] - 1s 957us/step - loss: 0.5698 - accuracy: 0.7473


In [106]:
best_accuracy

0.799

In [107]:
best_parameters

{'batch_size': 32, 'nb_epoch': 500, 'optimizer': 'adam'}